version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y strace
      - env
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - strace -p $(pgrep agent) -e trace=write -s 1000 &
      - codebuild-breakpoint
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo "called from codebuild on ${date}." > myartifact.txt
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - codebuild-breakpoint
artifacts:
  files:
    - myartifact.txt
  discard-paths: yes
