version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y strace
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - strace -p $(pgrep agent) -e write=all > /tmp/strace.log &
      - codebuild-breakpoint
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo "called from codebuild on ${date}." > myartifact.txt
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - codebuild-breakpoint
      - pkill strace
      - wc -l /tmp/strace.log
      - cat /tmp/strace.log
artifacts:
  files:
    - myartifact.txt
  discard-paths: yes
