version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - codebuild-breakpoint
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo "called from codebuild on ${date}." > myartifact.txt
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - myartifact.txt
  discard-paths: yes
